### PR TITLE
update key text_only_cpe with non_rpm_cpe

### PR DESCRIPTION
**Pull request by Ximinhan**
fix the error
```
>>> from errata_tool import Erratum
>>> et=Erratum(errata_id=116588)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/errata_tool/erratum.py", line 132, in __init__
    self._fetch(kwargs['errata_id'])
  File "/home/user/.local/lib/python3.8/site-packages/errata_tool/erratum.py", line 297, in _fetch
    self.text_only_cpe = content['text_only_cpe']
KeyError: 'text_only_cpe'
```

### CODE REVIEW

**Comment by Odilhao** [comment]
Applying the patch fixed the errata creation for me

**Comment by ktdreyer** [comment]
Could you please drop your py27 removal commit?

I see further discussion of this API breakage in https://issues.redhat.com/browse/CWFCONF-3820.

The problem is that if we simply drop this attribute, we break all our callers also.

**Comment by ktdreyer** [comment]
Looks like the ET team hotfixed this in https://issues.redhat.com/browse/CWFCONF-4719

**Comment by Ximinhan** [comment]
https://issues.redhat.com/browse/CWFCONF-4719 is to bring the field back, I will check if it's back

**Comment by Ximinhan** [comment]
I saw the field text_only_cpe is [back](https://errata.devel.redhat.com/api/v1/erratum/116833), so this pr is not necessary now.

**Pull request closed without merging**
