### PR TITLE
Populate advisory jira_issues field

### PR DESCRIPTION
**Pull request by thegreyd**

### CODE REVIEW

**Comment by thegreyd** [comment]
@ktdreyer Hi Ken, this is regarding https://issues.redhat.com/browse/ART-3818 . OCP as a product is transitioning from Bugzilla to JIRA for bug tracking. As part of that effort, JIRA issues will be a mainstay for our release advisories. Please review this change, happy to answer if you had any questions.

**Comment by ktdreyer** [comment]
Thanks for your patience. I inspected the REST API and it looks like the ET populates this for all advisories, even those that don't use Jira. So it looks good to me.

**Comment by ktdreyer** [comment]
I will tag a new release Monday with this change.

**Comment by ktdreyer** [comment]
I've pushed tag [`v1.27.0`](https://github.com/red-hat-storage/errata-tool/releases/tag/v1.27.0) for this.

**Pull request merged**
