### PR TITLE
erratum: Add RHSA support

### PR DESCRIPTION
**Pull request by lhh**
Signed-off-by: Lon Hohberger <lhh@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
What should we put in the docs for this new `security_impact` keyword argument?

**Comment by ktdreyer** [comment]
Oh I see, it just needs to be one of the following: None, or a string `Low`, `Moderate`, `Important`, `Critical`

**Comment by fuzzball81** [comment]
Do we need to add embargo date support as well?

**Comment by lhh** [comment]
That's already there; date parameter. The embargo date is not part of
errata tool info, so user must provide it.

**Comment by lhh** [comment]
That is, date can't be discerned from ET, you must tell ET date when filing.

**Comment by fuzzball81** [comment]
Thanks for the clarification! Everything looks good to me for merge.

**Pull request merged**
